<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Nekolla.Nekostick.Supervision</AssemblyName>
    <RootNamespace>Nekolla.Nekostick.Supervision</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nekolla.Nekostick.Contracts\Nekolla.Nekostick.Contracts.csproj" />
    <ProjectReference Include="..\Nekolla.Nekostick.Domain\Nekolla.Nekostick.Domain.csproj" />
  </ItemGroup>
</Project>
