// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nekolla.Nekostick.Persistence;

#nullable disable

namespace Nekolla.Nekostick.Persistence.Migrations;

[DbContext(typeof(NekostickDbContext))]
[Migration("20260907130000_AddWaitingServiceRuntimeState")]
partial class AddWaitingServiceRuntimeState
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        NekostickDbContext.BuildModel(modelBuilder);
    }
}
