// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nekolla.Nekostick.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nekolla.Nekostick.Persistence.Migrations
{
    [DbContext(typeof(NekostickDbContext))]
    [Migration("20260818230804_AddRequestLimitsAndRatePolicies")]
    partial class AddRequestLimitsAndRatePolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nekostick")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ConfigurationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("committed_at");

                    b.Property<string>("CommittedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("committed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("RevisionKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("revision_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_configuration_revisions");

                    b.HasIndex("RevisionKey")
                        .IsUnique()
                        .HasDatabaseName("ux_configuration_revisions_revision_key");

                    b.ToTable("configuration_revisions", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_configuration_revisions_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_configuration_revisions_singleton", "id = '018f0f00-0000-7000-8000-000000000001'::uuid AND revision_key = 'global'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0f00-0000-7000-8000-000000000001"),
                            CommittedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CommittedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RevisionKey = "global",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ExtensionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtensionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("extension_id");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("installed_version");

                    b.Property<string>("LoadState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("load_state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_extension_records");

                    b.HasIndex("ExtensionId")
                        .IsUnique()
                        .HasDatabaseName("ux_extension_records_extension_id");

                    b.ToTable("extension_records", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_extension_records_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_extension_records_load_state", "load_state IN ('Discovered', 'Loaded', 'Stopped', 'Failed', 'Unloading')");

                            t.HasCheckConstraint("ck_extension_records_text", "length(extension_id) BETWEEN 1 AND 128 AND length(installed_version) BETWEEN 1 AND 128");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ExtensionSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExtensionRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("extension_record_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_extension_settings");

                    b.HasIndex("ExtensionRecordId")
                        .IsUnique()
                        .HasDatabaseName("ux_extension_settings_extension_record_id");

                    b.ToTable("extension_settings", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_extension_settings_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_extension_settings_json", "jsonb_typeof(settings_json) IS NOT NULL AND octet_length(settings_json::text) <= 1048576");

                            t.HasCheckConstraint("ck_extension_settings_schema_version", "schema_version >= 0");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AutoPortRangeEnd")
                        .HasColumnType("integer")
                        .HasColumnName("auto_port_range_end");

                    b.Property<int>("AutoPortRangeStart")
                        .HasColumnType("integer")
                        .HasColumnName("auto_port_range_start");

                    b.Property<int?>("ClientIpRateQueueLimit")
                        .HasColumnType("integer")
                        .HasColumnName("client_ip_rate_queue_limit");

                    b.Property<string>("ClientIpRateRejectionBehavior")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("client_ip_rate_rejection_behavior");

                    b.Property<int?>("ClientIpRateReplenishmentPeriodMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("client_ip_rate_replenishment_period_milliseconds");

                    b.Property<string>("ClientIpRateRetryAfterBehavior")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_ip_rate_retry_after_behavior");

                    b.Property<long?>("ClientIpRateTokenLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("client_ip_rate_token_limit");

                    b.Property<long?>("ClientIpRateTokensPerPeriod")
                        .HasColumnType("bigint")
                        .HasColumnName("client_ip_rate_tokens_per_period");

                    b.Property<int>("ConfigurationPollIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("configuration_poll_interval_seconds");

                    b.Property<int>("ConnectTimeoutMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10000)
                        .HasColumnName("connect_timeout_milliseconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("HttpActivityTimeoutMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30000)
                        .HasColumnName("http_activity_timeout_milliseconds");

                    b.Property<int>("HttpTotalTimeoutMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100000)
                        .HasColumnName("http_total_timeout_milliseconds");

                    b.Property<int>("MaxConcurrentRequests")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_requests");

                    b.Property<long>("MaxRequestBodyBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_request_body_bytes");

                    b.Property<long>("MaxRequestHeaderBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_request_header_bytes");

                    b.Property<int>("RequestReadTimeoutMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("request_read_timeout_milliseconds");

                    b.Property<string>("TrustedProxyCidrsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trusted_proxy_cidrs_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.Property<int>("WebSocketIdleTimeoutMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120000)
                        .HasColumnName("websocket_idle_timeout_milliseconds");

                    b.HasKey("Id")
                        .HasName("pk_global_settings");

                    b.ToTable("global_settings", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_global_settings_client_ip_rate_policy", "(client_ip_rate_token_limit IS NULL AND client_ip_rate_tokens_per_period IS NULL AND client_ip_rate_replenishment_period_milliseconds IS NULL AND client_ip_rate_queue_limit IS NULL AND client_ip_rate_rejection_behavior IS NULL AND client_ip_rate_retry_after_behavior IS NULL) OR (client_ip_rate_token_limit > 0 AND client_ip_rate_tokens_per_period > 0 AND client_ip_rate_tokens_per_period <= client_ip_rate_token_limit AND client_ip_rate_replenishment_period_milliseconds BETWEEN 1 AND 86400000 AND client_ip_rate_queue_limit >= 0 AND client_ip_rate_rejection_behavior IN ('Reject', 'Queue') AND client_ip_rate_retry_after_behavior IN ('None', 'FromReplenishmentPeriod'))");

                            t.HasCheckConstraint("ck_global_settings_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_global_settings_limits", "max_request_body_bytes > 0 AND max_request_header_bytes > 0 AND max_concurrent_requests > 0 AND configuration_poll_interval_seconds > 0 AND request_read_timeout_milliseconds BETWEEN 1 AND 86400000");

                            t.HasCheckConstraint("ck_global_settings_max_request_header_bytes", "max_request_header_bytes <= 32768");

                            t.HasCheckConstraint("ck_global_settings_port_range", "auto_port_range_start BETWEEN 1 AND 65535 AND auto_port_range_end BETWEEN 1 AND 65535 AND auto_port_range_start <= auto_port_range_end");

                            t.HasCheckConstraint("ck_global_settings_proxy_timeouts", "connect_timeout_milliseconds BETWEEN 1 AND 86400000 AND http_activity_timeout_milliseconds BETWEEN 1 AND 86400000 AND http_total_timeout_milliseconds BETWEEN 1 AND 86400000 AND websocket_idle_timeout_milliseconds BETWEEN 1 AND 86400000");

                            t.HasCheckConstraint("ck_global_settings_singleton", "id = '018f0f00-0000-7000-8000-000000000002'::uuid");

                            t.HasCheckConstraint("ck_global_settings_trusted_proxy_cidrs_json", "jsonb_typeof(trusted_proxy_cidrs_json) = 'array' AND octet_length(trusted_proxy_cidrs_json::text) <= 262144");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0f00-0000-7000-8000-000000000002"),
                            AutoPortRangeEnd = 29999,
                            AutoPortRangeStart = 20000,
                            ConfigurationPollIntervalSeconds = 30,
                            ConnectTimeoutMilliseconds = 10000,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HttpActivityTimeoutMilliseconds = 30000,
                            HttpTotalTimeoutMilliseconds = 100000,
                            MaxConcurrentRequests = 1024,
                            MaxRequestBodyBytes = 31457280L,
                            MaxRequestHeaderBytes = 32768L,
                            RequestReadTimeoutMilliseconds = 30000,
                            TrustedProxyCidrsJson = "[]",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L,
                            WebSocketIdleTimeoutMilliseconds = 120000
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("LastConfigurationVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("last_configuration_version");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<string>("RuntimeState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("runtime_state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasAlternateKey("NodeId")
                        .HasName("ak_nodes_node_id");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("ux_nodes_default_node_id_active")
                        .HasFilter("node_id = '0' AND is_active");

                    b.ToTable("nodes", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_nodes_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_nodes_node_id", "length(node_id) BETWEEN 1 AND 128");

                            t.HasCheckConstraint("ck_nodes_versions", "last_configuration_version >= 0 AND length(runtime_state) BETWEEN 1 AND 32");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.PortLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<DateTimeOffset>("RenewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("renewed_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_port_leases");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_port_leases_service_id");

                    b.HasIndex("NodeId", "Port")
                        .IsUnique()
                        .HasDatabaseName("ux_port_leases_node_id_port");

                    b.ToTable("port_leases", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_port_leases_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_port_leases_port", "port BETWEEN 1 AND 65535");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ClientIpRateQueueLimit")
                        .HasColumnType("integer")
                        .HasColumnName("client_ip_rate_queue_limit");

                    b.Property<string>("ClientIpRateRejectionBehavior")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("client_ip_rate_rejection_behavior");

                    b.Property<int?>("ClientIpRateReplenishmentPeriodMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("client_ip_rate_replenishment_period_milliseconds");

                    b.Property<string>("ClientIpRateRetryAfterBehavior")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_ip_rate_retry_after_behavior");

                    b.Property<long?>("ClientIpRateTokenLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("client_ip_rate_token_limit");

                    b.Property<long?>("ClientIpRateTokensPerPeriod")
                        .HasColumnType("bigint")
                        .HasColumnName("client_ip_rate_tokens_per_period");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ExtensionHandlerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("extension_handler_id");

                    b.Property<string>("ForwardingMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("forwarding_mode");

                    b.Property<string>("HostPatternsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("host_patterns_json");

                    b.Property<string>("MatcherType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("matcher_type");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MethodsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("methods_json");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("pattern");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ReplaceTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("replace_template");

                    b.Property<string>("RequestHeaderRewritesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_header_rewrites_json");

                    b.Property<string>("ResponseHeaderRewritesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_header_rewrites_json");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("StaticRootPath")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("static_root_path");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_routes_service_id");

                    b.HasIndex("Enabled", "MatcherType", "Priority")
                        .HasDatabaseName("ix_routes_enabled_matcher_type_priority");

                    b.ToTable("routes", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_routes_client_ip_rate_policy", "(client_ip_rate_token_limit IS NULL AND client_ip_rate_tokens_per_period IS NULL AND client_ip_rate_replenishment_period_milliseconds IS NULL AND client_ip_rate_queue_limit IS NULL AND client_ip_rate_rejection_behavior IS NULL AND client_ip_rate_retry_after_behavior IS NULL) OR (client_ip_rate_token_limit > 0 AND client_ip_rate_tokens_per_period > 0 AND client_ip_rate_tokens_per_period <= client_ip_rate_token_limit AND client_ip_rate_replenishment_period_milliseconds BETWEEN 1 AND 86400000 AND client_ip_rate_queue_limit >= 0 AND client_ip_rate_rejection_behavior IN ('Reject', 'Queue') AND client_ip_rate_retry_after_behavior IN ('None', 'FromReplenishmentPeriod'))");

                            t.HasCheckConstraint("ck_routes_enum_values", "matcher_type IN ('Exact', 'ExactCaseInsensitive', 'Prefix', 'PrefixCaseInsensitive', 'Regex') AND target_type IN ('Microservice', 'StaticFile', 'ExtensionHandler') AND forwarding_mode IN ('Preserve', 'Strip', 'Replace')");

                            t.HasCheckConstraint("ck_routes_forwarding_template", "(forwarding_mode = 'Replace' AND replace_template IS NOT NULL AND length(replace_template) <= 4096) OR (forwarding_mode <> 'Replace' AND replace_template IS NULL)");

                            t.HasCheckConstraint("ck_routes_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_routes_matcher_json", "jsonb_typeof(host_patterns_json) = 'array' AND jsonb_typeof(methods_json) = 'array' AND octet_length(host_patterns_json::text) <= 262144 AND octet_length(methods_json::text) <= 262144");

                            t.HasCheckConstraint("ck_routes_pattern_length", "length(pattern) BETWEEN 1 AND 4096");

                            t.HasCheckConstraint("ck_routes_rewrite_metadata_json", "jsonb_typeof(request_header_rewrites_json) = 'array' AND jsonb_typeof(response_header_rewrites_json) = 'array' AND jsonb_typeof(metadata_json) = 'object' AND octet_length(request_header_rewrites_json::text) <= 1048576 AND octet_length(response_header_rewrites_json::text) <= 1048576 AND octet_length(metadata_json::text) <= 1048576");

                            t.HasCheckConstraint("ck_routes_target_reference", "(target_type = 'Microservice' AND service_id IS NOT NULL AND target_id = service_id::text AND static_root_path IS NULL AND extension_handler_id IS NULL) OR (target_type = 'StaticFile' AND service_id IS NULL AND target_id = static_root_path AND static_root_path IS NOT NULL AND extension_handler_id IS NULL) OR (target_type = 'ExtensionHandler' AND service_id IS NULL AND target_id = extension_handler_id AND static_root_path IS NULL AND extension_handler_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArgumentListJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("argument_list_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("EnvironmentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("environment_json");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("file_name");

                    b.Property<string>("HealthCheckHttpPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("health_check_http_path");

                    b.Property<int>("HealthCheckTimeoutMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("health_check_timeout_milliseconds");

                    b.Property<string>("HealthCheckType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("health_check_type");

                    b.Property<string>("RestartPolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("restart_policy");

                    b.Property<string>("StartMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("start_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("working_directory");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_services_enabled");

                    b.ToTable("services", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_services_enum_values", "start_mode IN ('Eager', 'Lazy') AND restart_policy IN ('Never', 'OnFailure', 'Always') AND health_check_type IN ('Process', 'Tcp', 'Http')");

                            t.HasCheckConstraint("ck_services_health", "health_check_timeout_milliseconds > 0 AND ((health_check_type = 'Http' AND health_check_http_path IS NOT NULL) OR (health_check_type <> 'Http' AND health_check_http_path IS NULL))");

                            t.HasCheckConstraint("ck_services_id_uuid_v7", "substring(id::text, 15, 1) = '7' AND substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_services_paths", "length(file_name) BETWEEN 1 AND 4096 AND length(working_directory) BETWEEN 1 AND 4096");

                            t.HasCheckConstraint("ck_services_process_json", "jsonb_typeof(argument_list_json) = 'array' AND jsonb_typeof(environment_json) = 'object' AND octet_length(argument_list_json::text) <= 1048576 AND octet_length(environment_json::text) <= 1048576");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ServiceRuntime", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("health");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle");

                    b.Property<int>("RestartCount")
                        .HasColumnType("integer")
                        .HasColumnName("restart_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("NodeId", "ServiceId")
                        .HasName("pk_service_runtimes");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_runtimes_service_id");

                    b.ToTable("service_runtimes", "nekostick", t =>
                        {
                            t.HasCheckConstraint("ck_service_runtimes_state", "lifecycle IN ('Disabled', 'Starting', 'Running', 'Stopping', 'Failed') AND health IN ('Unknown', 'Healthy', 'Unhealthy') AND restart_count >= 0");
                        });
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ExtensionSetting", b =>
                {
                    b.HasOne("Nekolla.Nekostick.Persistence.Entities.ExtensionRecord", "ExtensionRecord")
                        .WithMany("Settings")
                        .HasForeignKey("ExtensionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_extension_settings_extension_records_extension_record_id");

                    b.Navigation("ExtensionRecord");
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.PortLease", b =>
                {
                    b.HasOne("Nekolla.Nekostick.Persistence.Entities.Node", "Node")
                        .WithMany("PortLeases")
                        .HasForeignKey("NodeId")
                        .HasPrincipalKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_port_leases_nodes_node_id");

                    b.HasOne("Nekolla.Nekostick.Persistence.Entities.Service", "Service")
                        .WithMany("PortLeases")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_port_leases_services_service_id");

                    b.Navigation("Node");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.Route", b =>
                {
                    b.HasOne("Nekolla.Nekostick.Persistence.Entities.Service", "Service")
                        .WithMany("Routes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_routes_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ServiceRuntime", b =>
                {
                    b.HasOne("Nekolla.Nekostick.Persistence.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_runtimes_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.ExtensionRecord", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.Node", b =>
                {
                    b.Navigation("PortLeases");
                });

            modelBuilder.Entity("Nekolla.Nekostick.Persistence.Entities.Service", b =>
                {
                    b.Navigation("PortLeases");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
