// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nekolla.Nekostick.Persistence;

#nullable disable

namespace Nekolla.Nekostick.Persistence.Migrations
{
    [DbContext(typeof(NekostickDbContext))]
    [Migration("20260828120000_AddDisabledExtensionLoadState")]
    partial class AddDisabledExtensionLoadState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            NekostickDbContext.BuildModel(modelBuilder);
        }
    }
}
