<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Nekolla.Nekostick.Proxy</AssemblyName>
    <RootNamespace>Nekolla.Nekostick.Proxy</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Nekolla.Nekostick.Contracts/Nekolla.Nekostick.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
