<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Fixtures.Microservice</AssemblyName>
    <RootNamespace>Nekolla.Nekostick.Tests.Fixtures.Microservice</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
</Project>
